from typing import List
from core.entidades import Medicamento
from utils.random import random


names_medicamento = [
    "ZIAGEN",
    "TYMLOS",
    "ORENCIA",
    "REOPRO",
    "CALQUENCE",
    "Nenhum nome comercial nos EUA",
    "PRECOSE",
    "SECTRAL",
    "DIAMOX",
    "ACETADOTE",
    "Nenhum nome comercial nos EUA",
    "SORIATANE",
    "TUDORZA PRESSAIR",
    "ZOVIRAX",
    "HUMIRA",
    "DIFFERIN",
    "HEPSERA",
    "ADENOCARD",
    "ADUHELM",
    "GILOTRIF",
    "EYLEA",
    "FABRAZYME",
    "ALBENZA",
    "TANZEUM",
    "PROVENTIL-HFA, VENTOLIN-HFA",
    "LASTACAFT",
    "PROLEUKIN",
    "ALECENSA",
    "CAMPATH",
    "FOSAMAX",
    "UROXATRAL",
    "PRALUENT",
    "TEKTURNA",
    "ZYLOPRIM",
    "AXERT",
    "NESINA",
    "LOTRONEX",
    "XANAX",
    "CAVERJECT, EDEX, MUSE",
    "ACTIVASE",
    "ENTEREG",
    "Nenhum nome comercial nos EUA",
    "LETAIRIS",
    "ETHYOL",
    "Nenhum nome comercial nos EUA",
    "MIDAMOR",
    "Nenhum nome comercial nos EUA",
    "NEXTERONE",
    "Nenhum nome comercial nos EUA",
    "NORVASC",
    "RYBREVANT",
    "Nenhum nome comercial nos EUA",
    "Nenhum nome comercial nos EUA",
    "AMOXIL",
    "AUGMENTIN",
    "ADDERALL XR 10",
    "ABELCET, AMBISOME",
    "Nenhum nome comercial nos EUA",
    "UNASYN",
    "AGRYLIN",
    "KINERET",
    "ARIMIDEX",
    "Andexxa",
    "ERAXIS",
    "EBANGA",
    "Nenhum nome comercial nos EUA",
    "ERLEADA",
    "ELIQUIS",
    "APOKYN",
    "IOPIDINE",
    "OTEZLA",
    "EMEND",
    "Nenhum nome comercial nos EUA",
    "BROVANA",
    "Nenhum nome comercial nos EUA",
    "R-GENE 10",
    "ABILIFY",
    "NUVIGIL",
    "COARTEM",
    "Nenhum nome comercial nos EUA",
    "ELSPAR",
    "DURLAZA",
    "Translarna",
    "REYATAZ",
    "TENORMIN",
    "TECENTRIQ",
    "STRATTERA",
    "LIPITOR",
    "MEPRON",
    "MALARONE",
    "Nenhum nome comercial nos EUA",
    "ATROPEN",
    "RIDAURA",
    "STENDRA",
    "AYVAKIT",
    "DOPTELET",
    "BAVENCIO",
    "YESCARTA",
    "VIDAZA",
    "IMURAN",
    "ASTELIN, OPTIVAR",
    "EDARBI",
    "ZITHROMAX",
    "AZACTAM",
    "Nenhum nome comercial nos EUA",
    "PHOSLYRA",
    "ARANESP",
    "PULMOZYME",
    "EPOGEN/PROCRIT",
    "COPAXONE",
    "INTRON A",
    "ALFERON",
    "PROVAYBLUE",
    "PALFORZIA",
    "PEGASYS",
    "PEGINTRON",
    "CUROSURF"
]

def get_medicamento():
    return random(array=names_medicamento)

def get_fabricante():
    return random(array=names_medicamento)

def get_medicamentos() -> List[Medicamento]:
    medicamentos = []

    for _ in range(0, 10):
        medicamentos.append(Medicamento(nome=get_medicamento(), fabricante=get_fabricante(), quantidade=10, validade='01/10/2024', valor=50.0) )

    return medicamentos
